EP.BulkMessage.Presentation.Web/Controllers/CampaignController.cs
using CsvHelper;
using Elmah;
using EP.BulkMessage.Presentation.Web.Entity;
using EP.BulkMessage.Presentation.Web.Entity.Enum;
using EP.BulkMessage.Presentation.Web.Helpers;
using EP.BulkMessage.Presentation.Web.Modules;
using EP.BulkMessage.Presentation.Web.ViewModel;
using EP.BulkMessage.Service.Domain.CampaignModule;
using EP.BulkMessage.Service.Entity;
using EP.BulkMessage.Service.Entity.Enum;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace EP.BulkMessage.Presentation.Web.Controllers
{
    [Authorize]
    [HandleErrorWithELMAH]
    public class CampaignController : Controller
    {
        //
        // GET: /Campaign/

        public ActionResult Index(int messageId = 0)
        {
            SetCampaignMessage(messageId);
            var campaigns = new CampaignModule().GetAllCampaigns().OrderByDescending(p => p.Id);
            return View(campaigns);
        }

        public ActionResult Schedules(int messageId = 0)
        {
            var schedules = new ScheduleService().GetSchedules().OrderBy(p => p.StartTime);
            return View(schedules);
        }

        [UserPermit(Permission = UserPermission.CreateCampaignPermission)]
        public ActionResult Create(int id = 0)
        {
            CampaignVM campaign = (id == 0) ? new CampaignVM() : new CampaignModule().GetCampaign(id);
            ViewBag.CampaignTypes = GetCampaignTypes();
            return View(campaign);
        }

        public ActionResult CreateSms()
        {
            return View(new CampaignVM(CampaignType.SMS));
        }

        public ActionResult CreateEmail()
        {
            return View(new CampaignVM(CampaignType.Email));
        }

        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase File)
        {
            string[] formats = new string[] { ".xls", ".xlsx", ".csv"};

            if (File != null && formats.Contains(Path.GetExtension(File.FileName)))
            {
                var headers = new CampaignModule().GetHeaders(File);
                ModelState.Clear();
                return View("FileHeaders", headers);
            }
            throw new ArgumentNullException("File corrupted");
        }

        [HttpPost]
        [UserPermit(Permission = UserPermission.CreateCampaignPermission)]
        public ActionResult Create(CampaignVM campaign)
        {
            try
            {
                ViewBag.CampaignTypes = GetCampaignTypes();
                if (ModelState.IsValid)
                {
                    ViewBag.CampaignTypes = GetCampaignTypes();
                    campaign.CreatedBy = User.Identity.Name;
                    var campaignModule = new CampaignModule();
                    var report = campaignModule.ValidateCampaign(campaign);
                    TempData["CampaignReport"] = report;
                    return View("Report", report.Validations);
                }
                ViewBag.Message = "Error in input. Please correct the errors";

                return View(campaign);
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex);
                ViewBag.Message = "Cannot create campaign";
                return View(campaign);

            }
        }

        [UserPermit(Permission = UserPermission.CreateCampaignPermission)]
        public ActionResult Save()
        {
            var report = (CampaignReport)TempData["CampaignReport"];
            var campaignModule = new CampaignModule();
            int campaignId = campaignModule.SaveCampaign(report);
            campaignModule.UpdateCampaignFile(campaignId);
            return RedirectToAction("Index", new { messageId = (int)ViewMessage.CampaignSaved });

        }

        [UserPermit(Permission = UserPermission.ApproveCampaignPermission)]
        public ActionResult ApprovalDetails(int id)
        {
            CampaignModule campaignModule = new CampaignModule();

            var campaign = campaignModule.GetCampaign(id);
            if (campaign.TypeId == (int)CampaignType.Email)
            {
                ViewBag.EmailList = campaignModule.GetCampaignEmails(campaign.Id);
            }
            else
            {
                ViewBag.SmsList = campaignModule.GetCampaignSmses(campaign.Id);
            }


            return View(campaign);
        }

        public ActionResult Details(int id)
        {
            CampaignModule campaignModule = new CampaignModule();

            var campaign = campaignModule.GetCampaign(id);
            int newStatus = 0, send = 0, failed = 0;

            if (campaign.TypeId == (int)CampaignType.Email)
            {
                var emailList = campaignModule.GetCampaignEmails(campaign.Id);
                if (emailList != null)
                {
                    newStatus = emailList.Where(p => p.StatusId == (int)MessageStatus.New).Count();
                    send = emailList.Where(p => p.StatusId == (int)MessageStatus.Send).Count();
                    failed = emailList.Where(p => p.StatusId == (int)MessageStatus.Failed).Count();
                }

            }
            else
            {
                var smsList = campaignModule.GetCampaignSmses(campaign.Id);
                if (smsList != null)
                {
                    newStatus = smsList.Where(p => p.StatusId == (int)MessageStatus.New).Count();
                    send = smsList.Where(p => p.StatusId == (int)MessageStatus.Send).Count();
                    failed = smsList.Where(p => p.StatusId == (int)MessageStatus.Failed).Count();
                }
            }
            ViewBag.NewStatus = newStatus.ToString();
            ViewBag.Send = send.ToString();
            ViewBag.Failed = failed.ToString();

            return View(campaign);
        }

        public FileResult Export(int campaignId, int statusId)
        {

            CampaignModule campaignModule = new CampaignModule();
            var campaign = campaignModule.GetCampaign(campaignId);
            string fileName = "export-" + campaign.Id + ".csv";
            var memoryStream = new MemoryStream();
            var streamWriter = new StreamWriter(memoryStream);
                if (campaign.TypeId == (int)CampaignType.Email)
                {
                    var emailList = campaignModule.GetCampaignEmails(campaign.Id).Where(p => p.StatusId == statusId);
                    using (var csv = new CsvWriter(streamWriter))
                    {
                        csv.WriteRecords(emailList);
                    }
                }
                else
                {
                    var smsList = campaignModule.GetCampaignSmses(campaign.Id).Where(p => p.StatusId == statusId);
                    using (var csv = new CsvWriter(streamWriter))
                    {
                        csv.WriteRecords(smsList);
                    }
                }

                MemoryStream newStream = new MemoryStream(memoryStream.ToArray());
                newStream.Seek(0, SeekOrigin.Begin);

                return File(newStream, "text/csv", fileName);
        }

        [UserPermit(Permission= UserPermission.ApproveCampaignPermission)]
        public ActionResult Approval()
        {
            var campaigns = new CampaignModule().GetAllCampaigns().OrderByDescending(p => p.Id);
            return View(campaigns);
        }

        [UserPermit(Permission = UserPermission.ApproveCampaignPermission)]
        public ActionResult Approve(int id)
        {
            var response = new CampaignModule().ApproveCampaign(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [UserPermit(Permission = UserPermission.ApproveCampaignPermission)]
        public ActionResult Reject(int id)
        {
            var response = new CampaignModule().RejectCampaign(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [UserPermit(Permission = UserPermission.DeleteCampaignPermission)]
        public ActionResult Delete(int id)
        {
            var response = new CampaignModule().DeleteCampaign(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Schedule(int id, DateTime scheduledDate, DateTime scheduledTime)
        {
            scheduledDate = scheduledDate.Add(scheduledTime.Subtract(scheduledTime.Date));
            var response = new CampaignModule().ScheduleCampaign(id, scheduledDate);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Stop(int id)
        {
            var response = new CampaignModule().StopCampaign(id);
            return Json(response, JsonRequestBehavior.AllowGet);
        }


        public ActionResult SendTestMsg(int id, string recepient)
        {
            var response = new CampaignModule().SendTestCampaign(id, recepient);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        private SelectList GetCampaignTypes()
        {
            var campaignTypes = new List<KeyValue>
            {
                new KeyValue{ Key= CampaignType.Email.ToString(), Value=((int)CampaignType.Email).ToString() },
                new KeyValue{ Key= CampaignType.SMS.ToString(), Value=((int)CampaignType.SMS).ToString() }
            };

            return new SelectList(campaignTypes, "Value", "Key");
        }

        private void SetCampaignMessage(int messageId)
        {
            string message = String.Empty;
            switch (messageId)
            {

                case (int)ViewMessage.CampaignSaved:
                    {
                        message = "Campaign has been saved successfully";
                        break;
                    }
                case (int)ViewMessage.CampaignFailed:
                    {

EP.BulkMessage.Presentation.Web/Views/Campaign/Approval.cshtml
@model IEnumerable<EP.BulkMessage.Presentation.Web.ViewModel.CampaignVM>

@{
    ViewBag.Title = "Approve";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section scripts{

    @Styles.Render("~/Content/themes/base/css")
    <link href="~/Content/jquery.timepicker.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.timepicker.min.js"></script>
    <script src="~/Scripts/campaign-main.js"></script>
    <script>
     

        
    </script>
}

@if (ViewBag.Message != null)
{
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                @ViewBag.Message
            </div>
        </section>
    }
}
<h2>Approve Campaigns </h2>
<div id="divCampaigns">
    <table>
        <tr>
            <th>Id
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>Created By
               
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>Remarks
            </th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td width="50px">CP-@item.Id
                </td>
                <td width="150px">
                  <b>@Html.ActionLink(item.Name, "ApprovalDetails", new { id = item.Id })</b>
                </td>
                <td class="tdType">
                    @if (item.TypeId == 1)
                    {
                        @:<img src="@Url.Content("~/Images/email.png")" width="20" height="20" title="Email" />
                }
                    else
                    {
                        @:<img src="@Url.Content("~/Images/sms.png")" width="20" height="20" title="SMS" />
                }
                    @*  <br />
            @Html.DisplayFor(modelItem => item.Type)*@
                </td>
                <td width="100px">
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td class="tdStatus">
                    @switch (item.StatusId)
                    {
                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.New):
                            {
                        @:<img src="@Url.Content("~/Images/new.png")" width="20" height="20" title="New" />
                                 break;
                            }


                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Approved):
                            {
                        @:<img src="@Url.Content("~/Images/approved.png")" width="20" height="20" title="Approved" />
                                 break;
                            }

                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Scheduled):
                            {
                        @:<img src="@Url.Content("~/Images/calendar.png")" width="20" height="20" title="Scheduled" />

                                break;
                            }

                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Progress):
                            {
                        @:<img src="@Url.Content("~/Images/ajax-loader-red.gif")" width="20" height="20" title="Progress" />
                                 break;
                            }

                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Stopped):
                            {
                        @:<img src="@Url.Content("~/Images/stop.png")" width="20" height="20" title="Stopped" />
                                 break;
                            }

                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Completed):
                            {
                        @:<img src="@Url.Content("~/Images/task_completed.png")" width="20" height="20" title="Completed" />
                                 break;
                            }

                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Rejected):
                            {
                        @:<img src="@Url.Content("~/Images/stop.png")" width="20" height="20" title="Rejected" />
                                 break;
                            }
                    }
                    <p class="small status">
                        @Html.DisplayFor(modelItem => item.Status)
                    </p>
                </td>
                <td width="250px">
                    @switch (item.StatusId)
                    {
                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.New):
                            {
                        <span class="small">Created on  @item.CreatedDate.ToShortDateString()</span>
                                break;
                            }


                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Approved):
                            {
                        <span class="small">Created on  @item.CreatedDate.ToShortDateString()</span>
                                break;
                            }

                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Scheduled):
                            {
                        <span class="small">Scheduled to run on
                        @Html.DisplayFor(modelItem => item.StatusDate)</span>    
                                break;
                            }

                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Progress):
                            {
                        <span class="small">Progess of:  @item.PercentComplete %</span>
                                break;
                            }


                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Completed):
                            {
                        <span class="small">Completed on:  @item.StatusDate </span>
                                break;
                            }

                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Stopped):
                            {
                        <span class="small">Stopped on  @item.StatusDate</span>
                                break;
                            }

                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.Rejected):
                            {
                        <span class="small">Rejected on  @item.StatusDate</span>
                                break;
                            }

                    }
                </td>
                <td width="100px" class="tdAction">
                    <input type="hidden" name="name" value="@item.Id" class="hdnCampId" />
                    <input type="hidden" name="name" value="@item.TypeId" class="hdnTypeId" />
                    @switch (item.StatusId)
                    {
                        case ((int)EP.BulkMessage.Service.Entity.Enum.CampaignStatus.New):
                            {
                        <a href="#" class="btnApprove">
                            <img src="~/Images/approve.png" width="17" height="13" title="Approve" /></a>
                        <a href="#" class="btnReject">
                            <img src="~/Images/delete.png" width="16" height="16" title="Reject" /></a>
                                break;
                            }
                    }

                    <a href="~/Campaign/ApprovalDetails/@item.Id">
                        <img src="~/Images/detail.png" width="16" height="16" title="Detail" /></a>

                </td>
            </tr>
        }

    </table>
</div>
<div id="dialogReject" class="dialog" title="Confirm to Reject">Are you sure you want to reject the campaign?</div>
<div id="dialogApprove" class="dialog" title="Confirm to Approve">Are you sure you want to approve the campaign?</div>

EP.BulkMessage.Presentation.Web/Views/Campaign/ApprovalDetails.cshtml
@model EP.BulkMessage.Presentation.Web.ViewModel.CampaignVM
@section scripts{

    @Styles.Render("~/Content/themes/base/css")

}
<fieldset>
    <legend>Campaign</legend>

    <div class="display-field">
        <h1>Campaign: @Html.DisplayFor(model => model.Name) </h1>
    </div>
    <div class="display-field">
        <h3>@Html.DisplayFor(model => model.Type) Campaign </h3>
    </div>
    <div class="display-label">
        Status Date :   @Html.DisplayFor(model => model.StatusDate)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.CreatedDate):  @Html.DisplayFor(model => model.CreatedDate)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.CreatedBy):   @Html.DisplayFor(model => model.CreatedBy)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Status): @Html.DisplayFor(model => model.Status)
    </div>
</fieldset>
<div class="action-menu">
    @Html.ActionLink("Back to List", "Approval")
</div>


@if (ViewBag.EmailList != null)
{
    Html.RenderPartial("EmailList", (IEnumerable<EP.BulkMessage.Service.Entity.Email>)ViewBag.EmailList);
}

@if (ViewBag.SmsList != null)
{
    Html.RenderPartial("SmsList", (IEnumerable<EP.BulkMessage.Service.Entity.Sms>)ViewBag.SmsList);
}

EP.BulkMessage.Presentation.Web/Views/Campaign/Copy of Create.cshtml
@model EP.BulkMessage.Presentation.Web.ViewModel.CampaignVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <link href="~/Content/jquery.timepicker.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.timepicker.min.js"></script>
    <script src="~/Scripts/tinymce/tiny_mce.js"></script>
    @Styles.Render("~/Content/themes/base/css")
    <script>
        tinyMCE.init({
            // General options
            mode: "textareas",
            theme: "advanced",
            plugins: "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",
            editor_selector: "text-tinymce",
            // Theme options
            theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,hr,removeformat,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,cleanup,code,preview",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,
            forced_root_block: ''
        });
        $(document).ready(function (e) {
            $("#ddlType").change(function (e) {
                if ($(this).val() == "1") {
                    $("#lblRecipientField").html("Email Field");
                    $("#liSubject").show();
                }
                else {
                    $("#lblRecipientField").html("Mobile Number Field");
                    $("#liSubject").hide();
                }
            });
            $(".datepicker").datepicker();
            $('#timepicker').timepicker({ 'scrollDefaultNow': true });

        });
    </script>


}
@if (ViewBag.Message != null)
{
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                @ViewBag.Message
            </div>
        </section>
    }
}

@using (Html.BeginForm("Create", "Campaign", FormMethod.Post, new { enctype = "multipart/form-data", id="create-campaign" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <h2>Create New Campaign</h2>
    <fieldset>
        <legend>Log in Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name)
<br />
                @Html.ValidationMessageFor(m => m.Name)
            </li>
            <li>
                @Html.LabelFor(m => m.File)
                <input type="file" name="File" value=" " accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
                <br />
                @Html.ValidationMessageFor(m => m.File)
            </li>
            <li>
                @Html.LabelFor(m => m.TypeId)
                @Html.DropDownListFor(m => m.TypeId, (SelectList)ViewBag.CampaignTypes, new { id = "ddlType" })
                <br />
                @Html.ValidationMessageFor(m => m.TypeId)
            </li>
            <li>
                <label id="lblRecipientField">
                    @if (Model.TypeId == 1)
                    {
                        <text>Email Field</text>
                    
                    }

                    else
                    {
                        <text>Mobile Number Field</text>
                    }

                </label>
                @Html.TextBoxFor(m => m.RecipientField)
                <br />
                @Html.ValidationMessageFor(m => m.RecipientField)
            </li>
           
            <li id="liSubject" style="@(Model.TypeId == 1 ? "" : "display:none")" class="clear">
                @Html.LabelFor(m => m.Subject)
                @Html.TextBoxFor(m => m.Subject)
                <br /> 
                @Html.ValidationMessageFor(m => m.Subject)
            </li>
            <li  class="clear">
                @Html.LabelFor(m => m.Content)
                @Html.TextAreaFor(m => m.Content, new { @class = "text-tinymce", id = "contentEditor" })
                @Html.ValidationMessageFor(m => m.Content)
            </li>
            
        </ol>
        <div class="form-button clear">
            @Html.HiddenFor(p => p.Id)
            <input type="submit" value="Validate" />
            <input type="button" value="Cancel" onclick="history.back();" />
        </div>
    </fieldset>
}

EP.BulkMessage.Presentation.Web/Views/Campaign/CreateEmail.cshtml
@model EP.BulkMessage.Presentation.Web.ViewModel.CampaignVM
@{
    Layout = null;
}

<h2>Email Campaign</h2>
@Html.Partial("FileUploader")
@using (Ajax.BeginForm("Create", "Campaign", new AjaxOptions { UpdateTargetId="divReport", OnSuccess="ShowReport" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <ol>
            <li>
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name)
                <br />
                @Html.ValidationMessageFor(m => m.Name)
            </li>
            <li>
                <label id="lblRecipientField">
                    Email Field
                </label>
                @Html.TextBoxFor(m => m.RecipientField)
                <br />
                @Html.ValidationMessageFor(m => m.RecipientField)
            </li>

            <li id="liSubject">
                @Html.LabelFor(m => m.Subject, new { id = "txtSubject" })
                @Html.TextBoxFor(m => m.Subject)
                <br />
                @Html.ValidationMessageFor(m => m.Subject)
            </li>
            <li class="clear" id="liContent">
                @Html.LabelFor(m => m.Content)
                @Html.TextAreaFor(m => m.Content, new { @class = "text-tinymce", id = "contentEditor" })
                @Html.ValidationMessageFor(m => m.Content)
            </li>


        </ol>
        <div class="form-button clear">
            @Html.HiddenFor(p => p.Id)
            @Html.HiddenFor(p => p.TypeId)
            @Html.HiddenFor(p => p.Type, new { id = "hdnType" })
            @Html.HiddenFor(p => p.FileName, new { id = "hdnFileName" })
            <input type="submit" value="Validate" />
            <input type="button" value="Cancel" onclick="history.back();" />
        </div>
    </fieldset>
}
<script>
    tinyMCE.init({
        // General options
        mode: "textareas",
        theme: "advanced",
        plugins: "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",
        editor_selector: "text-tinymce",
        // Theme options
        theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,hr,removeformat,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,cleanup,code,preview",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_resizing: true,
        forced_root_block: '',
    });
</script>

EP.BulkMessage.Presentation.Web/Views/Campaign/CreateSms.cshtml
@model EP.BulkMessage.Presentation.Web.ViewModel.CampaignVM
@{
    Layout = null;
}
<h2>Sms Campaign</h2>
@Html.Partial("FileUploader")
@using (Ajax.BeginForm("Create", "Campaign", new AjaxOptions { UpdateTargetId="divReport", OnSuccess="ShowReport" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <ol>
            <li>
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name)
                <br />
                @Html.ValidationMessageFor(m => m.Name)
            </li>
            <li>
                <label id="lblRecipientField">
                    Mobile Number Field
                </label>
                @Html.TextBoxFor(m => m.RecipientField)
                <br />
                @Html.ValidationMessageFor(m => m.RecipientField)
            </li>

            <li id="liSubject" style="@(Model.TypeId == 1 ? "" : "display:none")" class="clear">
                @Html.LabelFor(m => m.Subject)
                @Html.TextBoxFor(m => m.Subject)
                <br />
                @Html.ValidationMessageFor(m => m.Subject)
            </li>
            <li class="clear" id="liContent">
                @Html.LabelFor(m => m.Content)
                @Html.TextAreaFor(m => m.Content,4, 50, new { maxlength = "300" })
                <i>Recommended message size is 160 letters</i>
                @Html.ValidationMessageFor(m => m.Content)
                
            </li>

        </ol>
        <div class="form-button clear">
            @Html.HiddenFor(p => p.Id)
            @Html.HiddenFor(p => p.TypeId)
            @Html.HiddenFor(p => p.Type, new { id = "hdnType" })
            @Html.HiddenFor(p => p.FileName, new { id = "hdnFileName" })
            <input type="submit" value="Validate" />
            <input type="button" value="Cancel" onclick="history.back();" />
        </div>
    </fieldset>
}

EP.BulkMessage.Presentation.Web/Views/Campaign/FileUploader.cshtml
@model EP.BulkMessage.Presentation.Web.ViewModel.CampaignVM
@{
    Layout = null;
}
@using (Html.BeginForm("UploadFile", "Campaign", FormMethod.Post, new { id = "formUpload" }))
{
    <fieldset>
        <ol>
            <li class="clear">
                <label>File</label>
                <input type="file" name="File" id="fileExcel" onchange="UploadFile(this);" value=" " accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
                <br />
                Selected file is: <b id="spanFileName"> <a href="~/data/campaign/@Model.FileName" target="_blank">@Model.FileName</a> </b>
            </li>
            <li id="liHeader"></li>
        </ol>
    </fieldset>
}

EP.BulkMessage.Presentation.Web/Views/Campaign/Report.cshtml
@model EP.BulkMessage.Presentation.Web.Validation.CampaignValidation

@{
    ViewBag.Title = "ImportReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int count = 1;
}

<h2>Campaign Validation Report</h2>
@using (Html.BeginForm("Save", "Campaign"))
{
    <fieldset>
        <legend>Campaign Validation</legend>

        <div class="display-label">
            Total Records:
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TotalRecordCount)
        </div>

        <div class="display-label">
            Records Failed:
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TotalRecordFailed)
        </div>
        <div class="form-button">
            @if (Model.IsValid)
            {
                <input type="submit" value="Submit" />
            }
            else
            {
                <h3 style="color: red">Not Valid</h3>
                <br />
            }

            <input type="button" onclick="history.back()" value="Cancel" />
        </div>
    </fieldset>
}
@if (Model.Messages.Any())
{
    <h2>Error Report</h2>
    <table>
        <tr>
            <th>Sl. No
            </th>
            <th>Field
            </th>
            <th>Row Number
            </th>
            <th>Error Message
            </th>

        </tr>
        @foreach (var item in Model.Messages)
        {
            <tr>
                <td width="50px">@count
                </td>
                <td width="100px">
                    @Html.DisplayFor(modelItem => item.ErrorInput)
                </td>
                <td width="100px">
                    @Html.DisplayFor(modelItem => item.RowNumber)
                </td>

                <td width="400px">
                    @Html.DisplayFor(modelItem => item.Message)
                </td>

            </tr>
            count += 1;
        }
    </table>
}